<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.sthorne.hytale.plugins</groupId>
    <artifactId>quickstacker</artifactId>
    <version>${revision}</version>

    <properties>
        <revision>1.3.0</revision>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <!-- Hytale release repository -->
        <!-- <repository>
            <id>hytale-release</id>
            <url>https://maven.hytale.com/release</url>
        </repository> -->
        <!-- Hytale pre-release repository -->
        <repository>
            <id>hytale-release</id>
            <url>https://maven.hytale.com/pre-release</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.hypixel.hytale</groupId>
            <artifactId>Server</artifactId>
            <!-- Replace with latest version, we provide jars for the last five releases -->
            <!-- Source https://maven.hytale.com/release/com/hypixel/hytale/Server/maven-metadata.xml -->
            <version>2026.02.26-7681d338c</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>